### ISSUE TITLE
Check feature

### ISSUE THREAD

**Issue by abs3nce** [FajsiEx/noter-client#89]
Would like to have the ability to make like check lists with boxes and check marks, I mean that is like one main thing that noter should have, the ability to make followup lists

Thx, abs3nce

**Comment by FajsiEx** [comment]
Already implemented with
```
- [ ] item
```

Styling is not fully done as isn't hotkeys or auto formatting... Will leave it open since those need to be done

**Comment by FajsiEx** [comment]
No point in auto indenting since we don't know what user wants
